create sequence hibernate_sequence start 1 increment 1;
create table tb_alunos (id int8 not null, endereço varchar(255), foto varchar(255), nome varchar(255), primary key (id));
create sequence hibernate_sequence start 1 increment 1;
create table tb_alunos (id int8 not null, endereço varchar(255), foto varchar(255), nome varchar(255), primary key (id));
create sequence hibernate_sequence start 1 increment 1;
create table tb_alunos (id int8 not null, endereço varchar(255), foto varchar(255), nome varchar(255), primary key (id));
create sequence hibernate_sequence start 1 increment 1;
create table tb_alunos (id int8 not null, endereço varchar(255), foto varchar(255), nome varchar(255), primary key (id));
create sequence hibernate_sequence start 1 increment 1;
create table tb_alunos (id int8 not null, endereço varchar(255), foto varchar(255), nome varchar(255), primary key (id));
